#!/bin/sh

set -e

composer update

if [ ! -d "PhpStorm" ]; then
    if [ ! -f "PhpStorm.tar.gz" ]; then
        wget -O PhpStorm.tar.gz https://download.jetbrains.com/webide/PhpStorm-2021.1.2.tar.gz
    fi
    tar -xzf PhpStorm.tar.gz --one-top-level --strip-components 1
fi

if [ ! -d "java" ]; then
    if [ ! -f "java.tar.gz" ]; then
        wget -O java.tar.gz https://javadl.oracle.com/webapps/download/AutoDL?BundleId=244575_d7fc238d0cbf4b0dac67be84580cfb4b
    fi
    tar -xzf java.tar.gz --one-top-level --strip-components 1
fi

if [ ! -d "test/.idea" ]; then
    mkdir test/.idea
fi

if [ -d "inspectionResults" ]; then
    rm -rf inspectionResults
fi

php_language_level_config='<?xml version="1.0" encoding="UTF-8"?><project version="4"><component name="PhpProjectSharedConfiguration" php_language_level="7.3" /></project>'

echo $php_language_level_config > test/.idea/php.xml

rm -rf ~/.cache/JetBrains

project_path=$(pwd)

echo About to run inspections with xml file: $project_path/exampleStandards.xml

PhpStorm/bin/phpstorm.sh inspect test $project_path/exampleStandards.xml inspectionResults -format json -v2

php inspect.php inspectionResults
