#!/bin/sh

set -e

composer install

vendor/bin/psalm
vendor/bin/phpcs src tests/behat/features/Context tests/phpunit --standard=PSR12
vendor/bin/phpstan analyse src tests/behat/features/Context tests/phpunit -l 8
